version: "3.9"
    
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    volumes:
        - ./jenkins_home:/var/jenkins_home
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - "8080:8080"
        - "50000:50000"

    # docker exec -u root -it 8ee464ea70cd bash
    # groupadd docker
    # usermod -aG docker jenkins
    # ls -lrth /var/run/docker.sock
    # chmod 666 /var/run/docker.sock
    
  sonarq:
    environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    image: sonarqube:latest
    ports:
        - "9000:9000"

  nexus:
    image: sonatype/nexus3
    ports:
        - "8081:8081"
        - "8082:8082"
    volumes:
      - ../nexus:/nexus-data



    
  